# This is a basic workflow that is manually triggered

name: Test:nft

on:
  push:
    paths-ignore:
      - "examples/**"
      - "README.md"
      - ".github/workflows/*.yml"
      - "packages/*/package.json"
      - "package.json"
      - "package-lock.json"
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache solana-localhost-devnet-keypair 
      id: cache-keypair
      uses: actions/cache@v3
      with:
        path: /tmp/solana-localhost-devnet-keypair
        key: ${{ runner.os }}-cache
    - run: npm ci
    - run: |
        cd ./packages/shared/
        NODE_ENV=standalone ./solana-suite-config.js debug on
        NODE_ENV=standalone ./solana-suite-config.js cluster custom $SOLANA_CUSTOM_URL
      env: 
        SOLANA_CUSTOM_URL: ${{secrets.SOLANA_CUSTOM_URL}}
    - run: |
        cd ./packages/shared/
        cat src/solana-suite.json
    - run: npm run test:nft
